[package]
name = "amanita"
version = "0.1.0"
edition = "2021"
authors = ["Ladislav Sladecek <ladislav.sladecek@gmail.com"]

[dependencies]
amanita-lib = { path = "../amanita-lib" }
rand_core = { version="0.6.4", features = ["getrandom"] }