[package]
name = "amanita-solana"
version = "0.1.0"
edition = "2021"
authors = ["Ladislav Sladecek <ladislav.sladecek@gmail.com"]

[dependencies]
solana-program = "1.17.13"
amanita-lib = { path = "../amanita-lib" }

[lib]
crate-type = ["cdylib", "lib"]